name: CI

on: [push, pull_request]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version:
        - "3.11"
        - "3.12"
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: |
          setup.cfg
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        python -m pip install -U -e '.[test]'
    - name: Test with pytest
      timeout-minutes: 30
      run: |
        python -m pytest -v --cov=src tests
    - name: Send code coverage report
      uses: codecov/codecov-action@v3
      with:
        env_vars: GHA_OS,GHA_PYTHON

  required-checks:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}

  deploy-to-pypi:
    needs: [test]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    environment: deploy-to-pypi-qedis
    permissions:
      id-token: write
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
        cache-dependency-path: |
          setup.cfg
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools
        pip install -U -e '.[build]'
    - name: Build sdist and wheel
      run: |
        python -m build -s -w
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
